function face_recognition_UI()
    %% ================ 界面初始化区 ================
    % 创建主窗口
    % Name: 窗口标题, NumberTitle: 是否显示Figure编号, Position: [x坐标 y坐标 宽度 高度]
    % Color: 背景颜色, MenuBar: 菜单栏显示, ToolBar: 工具栏显示
    mainFig = figure('Name', '基于PCA的人脸识别实验平台', ...
                    'NumberTitle', 'off', ...
                    'Position', [100, 100, 1200, 700], ...
                    'Color', [0.1, 0.1, 0.15], ...
                    'MenuBar', 'figure', ...
                    'ToolBar', 'figure');
    
    %% ================ 背景设置区 ================
    % 加载紫色星空背景
    try
        bgImg = imread('星空背景.jpg'); % 请确保此文件存在或替换为您的背景图片路径
    catch
        % 如果找不到背景图片，创建一个紫色渐变背景
        [X, Y] = meshgrid(1:1200, 1:700);
        bgImg = uint8(zeros(700, 1200, 3));
        bgImg(:,:,1) = uint8(50 + 30*sin(X/100) + 20*cos(Y/100));  % R通道
        bgImg(:,:,2) = uint8(10 + 10*sin(X/120));                  % G通道
        bgImg(:,:,3) = uint8(80 + 50*sin(X/200) + 40*cos(Y/80));   % B通道
    end
    
    % 创建背景图像对象
    % Parent: 父容器, Position: [左 下 宽 高](归一化坐标)
    bgAxes = axes('Parent', mainFig, 'Position', [0, 0, 1, 1]);
    image(bgImg);
    axis off;
    hold on;
    
    % % 创建半透明覆盖层，使UI元素更加清晰
    % % Position: [左 下 宽 高](归一化坐标), BackgroundColor: 背景颜色[R G B 透明度]
    % % BorderType: 边框类型
    % overlay = uipanel('Parent', mainFig, ...
    %                  'Position', [0.05, 0.05, 0.9, 0.9], ...
    %                  'BackgroundColor', [1, 1, 1, 0.1], ... % 修改为白色，透明度0.5
    %                  'BorderType', 'none');
    % set(overlay, 'BackgroundColor', [1, 1, 1]); % 设置为白色
    % alpha(overlay, 0.5); % 降低透明度，使背景更加可见

    
    % 创建标题
    % Style: 控件类型, String: 显示文本, Position: [x y 宽 高](像素坐标)
    % BackgroundColor: 背景颜色, ForegroundColor: 文字颜色
    % FontSize: 字体大小, FontWeight: 字体粗细
    % 创建标题
    titleText = uicontrol('Style', 'text', ...
                         'String', '基于PCA的人脸识别实验平台', ...
                         'Position', [400, 650, 400, 30], ...
                         'BackgroundColor', 'none', ... % 已经是透明的
                         'ForegroundColor', [1, 1, 1], ...
                         'FontSize', 16, ...
                         'FontWeight', 'bold');
    
    %% --- 1. 图像显示区 ---
    % Title: 面板标题, TitlePosition: 标题位置, FontSize: 字体大小
    % FontWeight: 字体粗细, BackgroundColor: 背景颜色[R G B 透明度]
    % ForegroundColor: 文字颜色, Position: [左 下 宽 高](归一化坐标)
    % BorderType: 边框类型, HighlightColor: 高亮颜色
    imgPanel = uipanel('Title', '图像显示区', ...
                      'TitlePosition', 'centertop', ...
                      'FontSize', 12, ...
                      'FontWeight', 'bold', ...
                      'BackgroundColor', [0.1, 0.1, 0.2, 0.7], ...
                      'ForegroundColor', [1, 1, 1], ...
                      'Position', [0.35, 0.2, 0.4, 0.6], ...
                      'BorderType', 'none', ...
                      'HighlightColor', [0.6, 0.4, 0.8]);
    
    % 图像显示区域
    % Parent: 父容器, Position: [左 下 宽 高](归一化坐标), Color: 背景颜色
    imgAxes = axes('Parent', imgPanel, ...
                  'Position', [0.05, 0.05, 0.9, 0.9], ...
                  'Color', [0.1, 0.1, 0.2]);
    axis(imgAxes, 'off');
    text(imgAxes, 0.5, 0.5, '请选择待识别图像', ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.7, 0.7, 0.7]);
    
    %% --- 2. 控制区 ---
    ctrlPanel = uipanel('Title', '控制区', ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 12, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor', [0.1, 0.1, 0.2, 0.7], ...
                       'ForegroundColor', [1, 1, 1], ...
                       'Position', [0.05, 0.6, 0.25, 0.2], ...
                       'BorderType', 'none', ...
                       'HighlightColor', [0.6, 0.4, 0.8]);
    
    % 选择输入待识别图像按钮
    % Parent: 父容器, Style: 控件类型, String: 显示文本
    % Position: [x y 宽 高](像素坐标), BackgroundColor: 背景颜色
    % ForegroundColor: 文字颜色, Callback: 回调函数
    inputBtn = uicontrol('Parent', ctrlPanel, ...
                        'Style', 'pushbutton', ...
                        'String', '选择图像', ...
                        'Position', [30, 80, 100, 30], ...
                        'BackgroundColor', [0.3, 0.2, 0.4], ...
                        'ForegroundColor', [1, 1, 1], ...
                        'Callback', @(src, event) face_recognition_functions('selectImage', mainFig, imgAxes));
    
    % 清除待识别图像按钮
    clearBtn = uicontrol('Parent', ctrlPanel, ...
                        'Style', 'pushbutton', ...
                        'String', '清除图像', ...
                        'Position', [150, 80, 100, 30], ...
                        'BackgroundColor', [0.3, 0.2, 0.4], ...
                        'ForegroundColor', [1, 1, 1], ...
                        'Callback', @(src, event) face_recognition_functions('clearImage', mainFig, imgAxes, cropSlider, rotateSlider, flipNone, flipHoriz, flipVert));
    
    % 开始识别按钮
    recognizeBtn = uicontrol('Parent', ctrlPanel, ...
                            'Style', 'pushbutton', ...
                            'String', '开始识别', ...
                            'Position', [90, 30, 100, 30], ...
                            'BackgroundColor', [0.4, 0.2, 0.6], ...
                            'ForegroundColor', [1, 1, 1], ...
                            'Callback', @(src, event) face_recognition_functions('startRecognition', mainFig, resultText, similarityText, matchAxes));
    
    %% --- 3. 图像参数化区 ---
    paramPanel = uipanel('Title', '图像参数化', ...
                        'TitlePosition', 'centertop', ...
                        'FontSize', 12, ...
                        'FontWeight', 'bold', ...
                        'BackgroundColor', [0.1, 0.1, 0.2, 0.5], ...
                        'ForegroundColor', [1, 1, 1], ...
                        'Position', [0.05, 0.2, 0.25, 0.35], ...
                        'BorderType', 'none', ...
                        'HighlightColor', [0.6, 0.4, 0.8]);
    
    % 裁切控制标签
    % Parent: 父容器, Style: 控件类型, String: 显示文本
    % Position: [x y 宽 高](像素坐标), BackgroundColor: 背景颜色
    % ForegroundColor: 文字颜色
    uicontrol('Parent', paramPanel, ...
             'Style', 'text', ...
             'String', '图像裁切:', ...
             'Position', [20, 150, 80, 20], ...
             'BackgroundColor', 'none', ... % 已经是透明的
             'ForegroundColor', [1, 1, 1]);
    
    % 裁切滑动条
    % Parent: 父容器, Style: 控件类型, Min: 最小值, Max: 最大值
    % Value: 当前值, Position: [x y 宽 高](像素坐标), Callback: 回调函数
    cropSlider = uicontrol('Parent', paramPanel, ...
                          'Style', 'slider', ...
                          'Min', 0.1, ...
                          'Max', 1, ...
                          'Value', 1, ...
                          'Position', [110, 150, 100, 20], ...
                          'Callback', @(src, event) face_recognition_functions('adjustCrop', mainFig, src, cropValueText));
    
    % 裁切值显示
    cropValueText = uicontrol('Parent', paramPanel, ...
                             'Style', 'text', ...
                             'String', '1.00', ...
                             'Position', [220, 150, 50, 20], ...
                             'BackgroundColor', 'none', ... % 已经是透明的
                             'ForegroundColor', [1, 1, 1], ...
                             'ButtonDownFcn', @(src, event) face_recognition_functions('directInputCrop', mainFig, cropSlider, cropValueText));

    % 旋转控制标签
    uicontrol('Parent', paramPanel, ...
             'Style', 'text', ...
             'String', '图像旋转:', ...
             'Position', [20, 110, 80, 20], ...
             'BackgroundColor', 'none', ... % 已经是透明的
             'ForegroundColor', [1, 1, 1]);
    
    % 旋转滑动条
    rotateSlider = uicontrol('Parent', paramPanel, ...
                            'Style', 'slider', ...
                            'Min', -180, ...
                            'Max', 180, ...
                            'Value', 0, ...
                            'Position', [110, 110, 100, 20], ...
                            'Callback', @(src, event) face_recognition_functions('adjustRotation', mainFig, src, rotateValueText));
    
    % 旋转值显示
    rotateValueText = uicontrol('Parent', paramPanel, ...
                              'Style', 'text', ...
                              'String', '0°', ...
                              'Position', [220, 110, 50, 20], ...
                              'BackgroundColor', 'none', ... % 已经是透明的
                              'ForegroundColor', [1, 1, 1], ...
                              'ButtonDownFcn', @(src, event) face_recognition_functions('directInputRotation', mainFig, rotateSlider, rotateValueText));
    
    % 翻转控制标签
    uicontrol('Parent', paramPanel, ...
             'Style', 'text', ...
             'String', '图像翻转:', ...
             'Position', [20, 70, 80, 20], ...
             'BackgroundColor', 'none', ... % 已经是透明的
             'ForegroundColor', [1, 1, 1]);
    
    % 独立的翻转选项按钮（不使用按钮组）
    flipNone = uicontrol('Parent', paramPanel, ...
                        'Style', 'radiobutton', ...
                        'String', '无', ...
                        'Position', [110, 70, 40, 20], ...
                        'BackgroundColor', [0.15, 0.15, 0.25], ... % 修改为透明
                        'ForegroundColor', [1, 0.8, 1], ...
                        'Value', 1, ...
                        'Callback', @(src, event) face_recognition_functions('flipImageDirect', mainFig, 'none', flipNone, flipHoriz, flipVert));
                        
    flipHoriz = uicontrol('Parent', paramPanel, ...
                         'Style', 'radiobutton', ...
                         'String', '水平', ...
                         'Position', [160, 70, 50, 20], ...
                         'BackgroundColor', [0.15, 0.15, 0.25], ... % 修改为透明
                         'ForegroundColor', [1, 0.8, 1], ...
                         'Callback', @(src, event) face_recognition_functions('flipImageDirect', mainFig, 'horizontal', flipNone, flipHoriz, flipVert));
                         
    flipVert = uicontrol('Parent', paramPanel, ...
                        'Style', 'radiobutton', ...
                        'String', '垂直', ...
                        'Position', [220, 70, 50, 20], ...
                        'BackgroundColor', [0.15, 0.15, 0.25], ... % 修改为透明
                        'ForegroundColor', [1, 0.8, 1], ...
                        'Callback', @(src, event) face_recognition_functions('flipImageDirect', mainFig, 'vertical', flipNone, flipHoriz, flipVert));
    
    % 应用参数按钮
    applyBtn = uicontrol('Parent', paramPanel, ...
                        'Style', 'pushbutton', ...
                        'String', '应用参数', ...
                        'Position', [40, 20, 100, 25], ...
                        'BackgroundColor', [0.3, 0.2, 0.4], ...
                        'ForegroundColor', [1, 1, 1], ...
                        'Callback', @(src, event) face_recognition_functions('applyParameters', mainFig, imgAxes));
    
    % 应用翻转按钮
    flipApplyBtn = uicontrol('Parent', paramPanel, ...
                           'Style', 'pushbutton', ...
                           'String', '应用翻转', ...
                           'Position', [150, 20, 100, 25], ...
                           'BackgroundColor', [0.3, 0.2, 0.4], ...
                           'ForegroundColor', [1, 1, 1], ...
                           'Callback', @(src, event) face_recognition_functions('applyFlip', mainFig, imgAxes));
    
    % 灰度化按钮
    grayBtn = uicontrol('Parent', paramPanel, ...
                        'Style', 'pushbutton', ...
                        'String', '灰度化', ...
                        'Position', [90, 50, 100, 25], ...
                        'BackgroundColor', [0.3, 0.2, 0.4], ...
                        'ForegroundColor', [1, 1, 1], ...
                        'Callback', @(src, event) face_recognition_functions('convertToGrayscale', mainFig, imgAxes));

    %% --- 4. 识别结果展示区 ---
    resultPanel = uipanel('Title', '识别结果', ...
                         'TitlePosition', 'centertop', ...
                         'FontSize', 12, ...
                         'FontWeight', 'bold', ...
                         'BackgroundColor', [0.1, 0.1, 0.2, 0.7], ...
                         'ForegroundColor', [1, 1, 1], ...
                         'Position', [0.8, 0.2, 0.15, 0.6], ...
                         'BorderType', 'none', ...
                         'HighlightColor', [0.6, 0.4, 0.8]);
    
    % 结果文本区域
    resultText = uicontrol('Parent', resultPanel, ...
                          'Style', 'text', ...
                          'String', '等待识别...', ...
                          'Position', [20, 300, 140, 30], ...
                          'BackgroundColor', 'none', ...
                          'ForegroundColor', [1, 1, 1], ...
                          'HorizontalAlignment', 'left');
    
    % 匹配图像显示区
    matchAxes = axes('Parent', resultPanel, ...
                    'Position', [0.1, 0.1, 0.8, 0.5], ...
                    'Color', [0.1, 0.1, 0.2]);
    axis(matchAxes, 'off');
    text(matchAxes, 0.5, 0.5, '匹配结果', ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.7, 0.7, 0.7]);
    
    % 相似度显示
    similarityText = uicontrol('Parent', resultPanel, ...
                              'Style', 'text', ...
                              'String', '相似度: --', ...
                              'Position', [20, 100, 140, 20], ...
                              'BackgroundColor', 'none', ...
                              'ForegroundColor', [1, 1, 1], ...
                              'HorizontalAlignment', 'left');
    
    %% ================ 数据初始化区 ================
    % 全局变量
    % originalImg: 原始图像, processedImg: 处理后的图像
    % cropFactor: 裁切因子, rotationAngle: 旋转角度, flipDir: 翻转方向
    userData = struct('originalImg', [], 'processedImg', [], 'cropFactor', 1, 'rotationAngle', 0, 'flipDir', 'none');
    setappdata(mainFig, 'UserData', userData);
end